import { osrsAssetUrl, surfAssetUrl } from './osrsAssetBase.js';

/** Vanilla OSRS UI sprites from melkypie/resource-packs (sample-vanilla branch). */
export const OSRS_ASSETS = {
  fixed: {
    windowTop: osrsAssetUrl('fixed_mode/window_frame_edge_top.png'),
    topRightCorner: osrsAssetUrl('fixed_mode/top_right_corner.png'),
    sidePanelBg: osrsAssetUrl('fixed_mode/side_panel_background.png'),
    sidePanelEdgeLeft: osrsAssetUrl('side_panel_edge_left.png'),
    sidePanelEdgeRight: osrsAssetUrl('side_panel_edge_right.png'),
    minimapFrame: osrsAssetUrl('fixed_mode/minimap_and_compass_frame.png'),
    minimapLeft: osrsAssetUrl('fixed_mode/minimap_left_edge.png'),
    minimapRight: osrsAssetUrl('fixed_mode/minimap_right_edge.png'),
    minimapBottom: osrsAssetUrl('fixed_mode/minimap_frame_bottom.png'),
    compassDial: osrsAssetUrl('other/compass.png'),
    tabsTop: osrsAssetUrl('fixed_mode/tabs_top_row.png'),
    tabsBottom: osrsAssetUrl('fixed_mode/tabs_row_bottom.png'),
  },
  chatbox: {
    background: osrsAssetUrl('chatbox/background.png'),
    stones: osrsAssetUrl('chatbox/buttons_background_stones.png'),
    button: osrsAssetUrl('chatbox/button.png'),
    buttonSelected: osrsAssetUrl('chatbox/button_selected.png'),
    buttonHovered: osrsAssetUrl('chatbox/button_hovered.png'),
  },
  tabs: {
    combat: osrsAssetUrl('tab/combat.png'),
    stats: osrsAssetUrl('tab/stats.png'),
    quests: osrsAssetUrl('tab/quests.png'),
    sailing: osrsAssetUrl('tab/sailing.png'),
    inventory: osrsAssetUrl('tab/inventory.png'),
    equipment: osrsAssetUrl('tab/equipment.png'),
    prayer: osrsAssetUrl('tab/prayer.png'),
    magic: osrsAssetUrl('tab/magic.png'),
    friends: osrsAssetUrl('tab/friends.png'),
    ignores: osrsAssetUrl('tab/ignores.png'),
    clanChannel: osrsAssetUrl('tab/clan_channel.png'),
    accountManagement: osrsAssetUrl('tab/account_management.png'),
    logout: osrsAssetUrl('tab/logout.png'),
    options: osrsAssetUrl('tab/options.png'),
    emotes: osrsAssetUrl('tab/emotes.png'),
    music: osrsAssetUrl('tab/music.png'),
    smallMiddle: osrsAssetUrl('tab/small_middle.png'),
    smallMiddleSelected: osrsAssetUrl('tab/small_middle_selected.png'),
    sideBorderTop: osrsAssetUrl('tab/side_border_top.png'),
    sideBorderMiddle: osrsAssetUrl('tab/side_border_middle.png'),
    sideBorderBottom: osrsAssetUrl('tab/side_border_bottom.png'),
  },
  /** OSRS-style surfboard icons (original pixel art for this project). */
  surf: {
    boardUpright: surfAssetUrl('board_upright.svg'),
    boardPlanted: surfAssetUrl('board_planted.svg'),
    ride: surfAssetUrl('board_ride.svg'),
    paddle: surfAssetUrl('board_paddle.svg'),
    reverse: surfAssetUrl('board_reverse.svg'),
    stanceGrind: surfAssetUrl('stance_grind.svg'),
    stanceTuck: surfAssetUrl('stance_tuck.svg'),
    stanceAir: surfAssetUrl('stance_air.svg'),
  },
  sailing: {
    steering: osrsAssetUrl('sailing/steering.png'),
    notSteering: osrsAssetUrl('sailing/not_steering.png'),
    tabStats: osrsAssetUrl('sailing/tab_stats.png'),
    tabFacilities: osrsAssetUrl('sailing/tab_facilities.png'),
    tabCrew: osrsAssetUrl('sailing/tab_crew.png'),
  },
  skill: {
    agility: osrsAssetUrl('skill/agility.png'),
    sailing: osrsAssetUrl('skill/sailing.png'),
  },
  button: {
    forward: osrsAssetUrl('button/forward_arrow.png'),
    back: osrsAssetUrl('button/back_arrow.png'),
  },
  chevron: {
    up: osrsAssetUrl('chevron/yellow_up_single.png'),
    upDouble: osrsAssetUrl('chevron/yellow_up_double.png'),
    down: osrsAssetUrl('chevron/yellow_down_single.png'),
    downStop: osrsAssetUrl('chevron/yellow_down_stop.png'),
  },
} as const;
